### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier '%.8f'

### ISSUE THREAD

**Issue by multikoop** [unterstein/binance-trader#1]
Running on MacOS 10.13, Java 1.8.0_151 
```
mvn spring-boot:run -DAPI_KEY='mykey' -DAPI_SECRET='mysecret' \
-DTRADE_PROFIT='1.3' -DTRADE_AMOUNT='75' \
-DBASE_CURRENCY='ETH' -DTRADE_CURRENCY='POE'
```

results in the following exception after a while

```
2017-12-30 13:56:40.877  INFO 8056 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Tradingbalance: AssetBalance[asset=POE,free=149.85000000,locked=0.00000000]
2017-12-30 13:56:40.877  INFO 8056 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Order filled
2017-12-30 13:56:40.877  INFO 8056 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Not gaining enough profit anymore, lets sell
2017-12-30 13:56:40.878 ERROR 8056 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Unable to perform ticker

java.util.MissingFormatArgumentException: Format specifier '%.8f'
	at java.util.Formatter.format(Formatter.java:2519) ~[na:1.8.0_151]
	at java.util.Formatter.format(Formatter.java:2455) ~[na:1.8.0_151]
	at java.lang.String.format(String.java:2940) ~[na:1.8.0_151]
	at io.github.unterstein.BinanceTrader.tick(BinanceTrader.java:97) ~[classes/:na]
```

I guess there is a parameter missing in the log info  (sellPrice).  If I find some time  will provide a PR.

Anyway, great work. Will check out the bot performance ;)

**Comment by unterstein** [comment]
Awesome report and pull request, thank you very much 👍
