### ISSUE TITLE
Price_Filter Problem

### ISSUE THREAD

**Issue by det-peralta** [unterstein/binance-trader#11]
I having trouble with this error. 

`com.binance.api.client.exception.BinanceApiException: Filter failure: PRICE_FILTER
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57) ~[binance-api-client-1.0.0.jar!/:na]
        at com.binance.api.client.impl.BinanceApiRestClientImpl.newOrder(BinanceApiRestClientImpl.java:103) ~[binance-api-client-1.0.0.jar!/:na]
        at io.github.unterstein.TradingClient.buy(TradingClient.java:66) ~[classes!/:0.0.1-SNAPSHOT]
        at io.github.unterstein.BinanceTrader.tick(BinanceTrader.java:55) ~[classes!/:0.0.1-SNAPSHOT]
        at io.github.unterstein.BinanceBotApplication.schedule(BinanceBotApplication.java:53) [classes!/:0.0.1-SNAPSHOT]`

i research an find out this page. However i cant understand how to fix it.
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

https://www.reddit.com/r/binance/comments/7941mc/binance_api_error/

Command example:
```
TRADE_PROFIT='1.3'
TRADE_AMOUNT='40'
BASE_CURRENCY='BNB' 
TRADE_CURRENCY='RCN'

```
 BNB Balance: 2.25157165

Can you help me?

**Comment by det-peralta** [comment]
can we set --increasing .00001 --decreasing .00001 ? To bypass the error?

**Comment by stevengehner** [comment]
2018-01-15 14:52:57.426  INFO 16 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : buyPrice:0.00325001 sellPrice:0.00332799 bid:0.00332800 ask:0.00332800 price:0.00325900 profit:0.00329226 diff:0.00003574

2018-01-15 14:52:57.426  INFO 16 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : nothing bought, let`s check
2018-01-15 14:52:57.426  INFO 16 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Buy detected
2018-01-15 14:52:57.426  INFO 16 --- [pool-1-thread-1] io.github.unterstein.TradingClient       : Buying 5 for 0.00325001

2018-01-15 14:52:57.705 ERROR 16 --- [pool-1-thread-1] io.github.unterstein.BinanceTrader       : Unable to perform ticker

com.binance.api.client.exception.BinanceApiException: Filter failure: PRICE_FILTER
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57) ~[binance-api-client-1.0.0.jar!/:na]
	at com.binance.api.client.impl.BinanceApiRestClientImpl.newOrder(BinanceApiRestClientImpl.java:103) ~[binance-api-client-1.0.0.jar!/:na]
	at io.github.unterstein.TradingClient.buy(TradingClient.java:66) ~[classes!/:0.0.1-SNAPSHOT]
	at io.github.unterstein.BinanceTrader.tick(BinanceTrader.java:55) ~[classes!/:0.0.1-SNAPSHOT]
	at io.github.unterstein.BinanceBotApplication.schedule(BinanceBotApplication.java:53) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]


-e TRADE_PROFIT='1.3' \
-e TRADE_AMOUNT='5' \
-e BASE_CURRENCY='ETH' \
-e TRADE_CURRENCY='TRIG' \
unterstein/binance-trader

**Comment by Minimalist77** [comment]
There is an Value Named "TRADE_DIFFERENCE" you can set this to:
TRADE_DIFFERENCE='.00001'
